service: pickle-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  stage: ${opt:stage, 'dev'}

  environment:
    TABLE_NAME: ${self:custom.tableName}
  
  
  deploymentBucket:
    name: serverless-deploy-397570188272-us-east-2
    serverSideEncryption: AES256


  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:UpdateItem
            - dynamodb:Scan
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/${self:custom.tableName}

  # ✅ httpApi MUST live under provider.httpApi
  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:5173
        - https://pickle.kyle-white.com
      allowedHeaders:
        - Authorization
        - Content-Type
      allowedMethods:
        - GET
        - POST
        - OPTIONS
      allowCredentials: false
    authorizers:
      cognitoAuthorizer:
        type: jwt
        identitySource: '$request.header.Authorization'
        # 👇 issuer MUST be pool endpoint (not Hosted UI)
        issuerUrl: https://cognito-idp.us-east-2.amazonaws.com/us-east-2_wvWmECk8W
        # 👇 audience MUST include your App Client ID (PickleballSPA)
        audience:
          - 5srl4gktjb9bvkm3np3n32c1ld

custom:
  tableName: ${self:service}-table-${sls:stage}

functions:
  postMatches:
    handler: src/matches.handler
    events:
      - httpApi:
          path: /matches
          method: POST
          authorizer:
            name: cognitoAuthorizer

  getStandings:
    handler: src/standings.handler
    events:
      - httpApi:
          path: /standings
          method: GET

resources:
  Resources:
    PickleTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - { AttributeName: PK, AttributeType: S }
          - { AttributeName: SK, AttributeType: S }
        KeySchema:
          - { AttributeName: PK, KeyType: HASH }
          - { AttributeName: SK, KeyType: RANGE }

plugins:
  - serverless-esbuild

package:
  individually: true

outputs:
  ApiUrl:
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com"
  TableName:
    Value: ${self:custom.tableName}
