service: pickle-api
frameworkVersion: '3'

plugins:
  - serverless-esbuild

params:
  dev:
    COGNITO_ISSUER_URL: https://cognito-idp.us-east-2.amazonaws.com/us-east-2_wvWmECk8W
    COGNITO_APP_CLIENT_ID: 5srl4gktjb9bvkm3np3n32c1ld
  prod:
    COGNITO_ISSUER_URL: https://cognito-idp.us-east-2.amazonaws.com/us-east-2_wvWmECk8W
    COGNITO_APP_CLIENT_ID: 5srl4gktjb9bvkm3np3n32c1ld

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  stage: ${opt:stage, 'dev'}
  httpApi:
    payload: '2.0'
    cors:
      allowedOrigins:
        - http://localhost:5173
        - https://pickle.kyle-white.com
      allowedHeaders:
        - Authorization
        - Content-Type
      allowedMethods:
        - GET
        - POST
        - DELETE
        - OPTIONS
        - PATCH
      allowCredentials: false
      maxAge: 1800
    authorizers:
      jwtAuth:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: ${param:COGNITO_ISSUER_URL}
        audience:
          - ${param:COGNITO_APP_CLIENT_ID}
  environment:
    TABLE_NAME: !Ref PickleballTable
    COGNITO_ISSUER_URL: ${param:COGNITO_ISSUER_URL}
    COGNITO_APP_CLIENT_ID: ${param:COGNITO_APP_CLIENT_ID}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:DeleteItem
            - dynamodb:TransactWriteItems
          Resource:
            - !GetAtt PickleballTable.Arn
            - !Sub '${PickleballTable.Arn}/index/*'

# ✅ esbuild bundling config must be TOP-LEVEL (not under provider)
custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    platform: node
    target: node20
    keepNames: true
    external: []        # bundle all deps, including @aws-sdk

# ✅ With esbuild bundling we do NOT ship node_modules
package:
  individually: true
  patterns:
    - src/**                 # include your source; esbuild will resolve imports
    - '!**/*.test.*'
    - '!**/__tests__/**'
    - package.json
    - package-lock.json
    - '!node_modules/**'     # important on Windows to avoid EMFILE

functions:
  # ---------- GET (PUBLIC; some may check auth in-Lambda) ----------
  listLeagues:
    handler: src/leagues_list.handler
    events:
      - httpApi:
          path: /leagues
          method: GET
          authorizer: jwtAuth

  listMatches:
    handler: src/matches_list.handler
    events:
      - httpApi:
          path: /leagues/{id}/matches
          method: GET

  getMetrics:
    handler: src/metrics_get.handler
    events:
      - httpApi:
          path: /leagues/{id}/metrics
          method: GET

  getStandings:
    handler: src/standings_get.handler
    events:
      - httpApi:
          path: /leagues/{id}/standings
          method: GET

  playersList:
    handler: src/players_list.handler
    events:
      - httpApi:
          path: /leagues/{id}/players
          method: GET

  getLeague:
    handler: src/league_get.handler
    events:
      - httpApi:
          path: /leagues/{id}
          method: GET

  publicLeagues:
    handler: src/leagues_public_list.handler
    events:
      - httpApi:
          path: /leagues/public
          method: GET

  # ---------- WRITE (OWNER-ONLY; protected by JWT authorizer) ----------
  createLeague:
    handler: src/leagues_create.handler
    events:
      - httpApi:
          path: /leagues
          method: POST
          authorizer: jwtAuth

  createMatch:
    handler: src/matches_create.handler
    events:
      - httpApi:
          path: /leagues/{id}/matches
          method: POST
          authorizer: jwtAuth

  deleteLastMatch:
    handler: src/matches_delete_last.handler
    events:
      - httpApi:
          path: /leagues/{id}/matches/last
          method: DELETE
          authorizer: jwtAuth

  renameLeague:
    handler: src/league_rename.handler
    events:
      - httpApi:
          path: /leagues/{id}
          method: PATCH
          authorizer: jwtAuth

resources:
  Conditions:
    IsProd:
      Fn::Equals:
        - ${sls:stage}
        - prod

  Resources:
    # Custom domain mapping for prod (optional)
    ApiApiMapping:
      Type: AWS::ApiGatewayV2::ApiMapping
      Condition: IsProd
      DependsOn: HttpApiStage
      Properties:
        ApiId: !Ref HttpApi
        DomainName: api.pickle.kyle-white.com
        Stage: !Ref HttpApiStage

    PickleballTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: pickleball-${sls:stage}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - { AttributeName: PK,    AttributeType: S }
          - { AttributeName: SK,    AttributeType: S }
          - { AttributeName: GSI1PK, AttributeType: S }
          - { AttributeName: GSI1SK, AttributeType: S }
          - { AttributeName: GSI2PK, AttributeType: S }
          - { AttributeName: GSI2SK, AttributeType: S }
          - { AttributeName: GSI3PK, AttributeType: S }
          - { AttributeName: GSI3SK, AttributeType: S }
        KeySchema:
          - { AttributeName: PK, KeyType: HASH }
          - { AttributeName: SK, KeyType: RANGE }
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - { AttributeName: GSI1PK, KeyType: HASH }
              - { AttributeName: GSI1SK, KeyType: RANGE }
            Projection: { ProjectionType: ALL }
          - IndexName: GSI2
            KeySchema:
              - { AttributeName: GSI2PK, KeyType: HASH }
              - { AttributeName: GSI2SK, KeyType: RANGE }
            Projection: { ProjectionType: ALL }
          - IndexName: GSI3
            KeySchema:
              - { AttributeName: GSI3PK, KeyType: HASH }
              - { AttributeName: GSI3SK, KeyType: RANGE }
            Projection: { ProjectionType: ALL }
