service: pickle-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-2
  stage: ${opt:stage, 'dev'}
  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:5173
        - https://pickle.kyle-white.com
      allowedHeaders:
        - Authorization
        - Content-Type
      allowedMethods:
        - GET
        - POST
        - OPTIONS

functions:
  listLeagues:
    handler: src/leagues_list.handler
    events:
      - httpApi:
          path: /leagues
          method: GET

  createLeague:
    handler: src/leagues_create.handler
    events:
      - httpApi:
          path: /leagues
          method: POST

  listMatches:
    handler: src/matches_list.handler
    events:
      - httpApi:
          path: /leagues/{id}/matches
          method: GET

  createMatch:
    handler: src/matches_create.handler
    events:
      - httpApi:
          path: /leagues/{id}/matches
          method: POST

  getMetrics:
    handler: src/metrics_get.handler
    events:
      - httpApi:
          path: /leagues/{id}/metrics
          method: GET

package:
  patterns:
    - src/**
    - '!node_modules/**'
