name: Deploy Pickle (Frontend)

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'

permissions:
  id-token: write
  contents: read

env:
  BUCKET: pickle.kyle-white.com
  DIST_ID: ${{ secrets.CLOUDFRONT_DIST_ID }}   

concurrency:
  group: frontend-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Show .env.production (redacted)
        working-directory: frontend
        run: sed -E 's/(=).+/\1***REDACTED***/' .env.production && echo && cat .env.production | grep VITE_COGNITO_USER_POOL_CLIENT_ID
      
      - name: Build
        run: npm run build
          grep -R "loginWith:{email:!0,oauth" dist/ -n || echo "NESTED oauth not found"

      - name: Verify build
        run: test -f dist/index.html

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::397570188272:role/github-oidc-deploy
          aws-region: us-east-2   # <— set to your S3 bucket’s region

      # (optional) clean any stray uploads
      - name: Clean accidental /src
        run: aws s3 rm s3://$BUCKET/src --recursive || true

      # Long-cache all built assets except index.html
      - name: Sync assets
        run: |
          aws s3 sync dist/ s3://$BUCKET --delete \
            --exclude "index.html" \
            --cache-control "public,max-age=31536000,immutable"

      # No-cache index.html so users see changes immediately
      - name: Upload index.html
        run: |
          aws s3 cp dist/index.html s3://$BUCKET/index.html \
            --cache-control "no-cache" --content-type "text/html"

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id "$DIST_ID" --paths "/*"