name: Deploy Pickle
on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

env:
  SOURCE_DIR: .                      
  BUCKET: pickle.kyle-white.com   
  DIST_ID: E3MBOAEFHOHU4            

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Sanity check the path
      - name: List files
        run: |
          echo "pwd=$(pwd)"
          ls -la
          echo "---- listing $SOURCE_DIR ----"
          ls -la "$SOURCE_DIR"

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::397570188272:role/github-oidc-deploy
          aws-region: us-east-1

      - name: Sync assets (long cache)
        run: |
          aws s3 sync "$SOURCE_DIR"/ s3://$BUCKET --delete \
            --exclude "index.html" \
            --cache-control "public,max-age=31536000,immutable"

      - name: Upload index.html (no cache)
        run: |
          aws s3 cp "$SOURCE_DIR"/index.html s3://$BUCKET/index.html \
            --cache-control "no-cache" --content-type "text/html"

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id $DIST_ID --paths "/*"