name: Deploy Pickleball App
on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Quick sanity: print repo/ref so you can match the trust policy
      - name: Debug GitHub context
        run: |
          echo "repo=${{ github.repository }}"
          echo "ref=${{ github.ref }}"

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm run build

      # (Optional) Print OIDC claims to see the exact `sub`
      - name: Show OIDC token claims
        run: |
          sudo apt-get update >/dev/null && sudo apt-get install -y jq >/dev/null
          TOKEN=$(curl -sSL -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com" | jq -r '.value')
          echo "::add-mask::$TOKEN"
          PAYLOAD=$(echo "$TOKEN" | cut -d '.' -f2 | tr '_-' '/+' | base64 -d 2>/dev/null || true)
          echo "OIDC payload: $PAYLOAD"

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::397570188272:role/github-oidc-deploy
          aws-region: us-east-1

      - name: Upload to S3
        run: aws s3 sync dist/ s3://pickle.kyle-white.com --delete

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id E3MBOAEFHOHU4 --paths "/*"