name: Deploy Pickleball App
on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug GitHub context   # 👈 Debug step
        run: |
          echo "repo=${{ github.repository }}"
          echo "ref=${{ github.ref }}"

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci
      - run: npm run build

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::397570188272:role/github-oidc-deploy
          aws-region: us-east-1

      - name: Upload to S3
        run: aws s3 sync dist/ s3://pickle.kyle-white.com --delete

      - name: Invalidate CloudFront
        run: aws cloudfront create-invalidation --distribution-id E3MBOAEFHOHU4 --paths "/*"